# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/wredenba/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/wredenba/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wredenba/git/PosixHALExample

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wredenba/git/PosixHALExample

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/wredenba/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/wredenba/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wredenba/git/PosixHALExample/CMakeFiles /home/wredenba/git/PosixHALExample//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wredenba/git/PosixHALExample/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PosixExample

# Build rule for target.
PosixExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PosixExample
.PHONY : PosixExample

# fast build rule for target.
PosixExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/build
.PHONY : PosixExample/fast

src/CHAL_SHARED/color_conv.o: src/CHAL_SHARED/color_conv.cpp.o
.PHONY : src/CHAL_SHARED/color_conv.o

# target to build an object file
src/CHAL_SHARED/color_conv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/color_conv.cpp.o
.PHONY : src/CHAL_SHARED/color_conv.cpp.o

src/CHAL_SHARED/color_conv.i: src/CHAL_SHARED/color_conv.cpp.i
.PHONY : src/CHAL_SHARED/color_conv.i

# target to preprocess a source file
src/CHAL_SHARED/color_conv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/color_conv.cpp.i
.PHONY : src/CHAL_SHARED/color_conv.cpp.i

src/CHAL_SHARED/color_conv.s: src/CHAL_SHARED/color_conv.cpp.s
.PHONY : src/CHAL_SHARED/color_conv.s

# target to generate assembly for a file
src/CHAL_SHARED/color_conv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/color_conv.cpp.s
.PHONY : src/CHAL_SHARED/color_conv.cpp.s

src/CHAL_SHARED/csal_ipc.o: src/CHAL_SHARED/csal_ipc.cpp.o
.PHONY : src/CHAL_SHARED/csal_ipc.o

# target to build an object file
src/CHAL_SHARED/csal_ipc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc.cpp.o
.PHONY : src/CHAL_SHARED/csal_ipc.cpp.o

src/CHAL_SHARED/csal_ipc.i: src/CHAL_SHARED/csal_ipc.cpp.i
.PHONY : src/CHAL_SHARED/csal_ipc.i

# target to preprocess a source file
src/CHAL_SHARED/csal_ipc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc.cpp.i
.PHONY : src/CHAL_SHARED/csal_ipc.cpp.i

src/CHAL_SHARED/csal_ipc.s: src/CHAL_SHARED/csal_ipc.cpp.s
.PHONY : src/CHAL_SHARED/csal_ipc.s

# target to generate assembly for a file
src/CHAL_SHARED/csal_ipc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc.cpp.s
.PHONY : src/CHAL_SHARED/csal_ipc.cpp.s

src/CHAL_SHARED/csal_ipc_message_publishqueue.o: src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.o
.PHONY : src/CHAL_SHARED/csal_ipc_message_publishqueue.o

# target to build an object file
src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.o
.PHONY : src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.o

src/CHAL_SHARED/csal_ipc_message_publishqueue.i: src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.i
.PHONY : src/CHAL_SHARED/csal_ipc_message_publishqueue.i

# target to preprocess a source file
src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.i
.PHONY : src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.i

src/CHAL_SHARED/csal_ipc_message_publishqueue.s: src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.s
.PHONY : src/CHAL_SHARED/csal_ipc_message_publishqueue.s

# target to generate assembly for a file
src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.s
.PHONY : src/CHAL_SHARED/csal_ipc_message_publishqueue.cpp.s

src/CHAL_SHARED/csal_ipc_message_subscribequeue.o: src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.o
.PHONY : src/CHAL_SHARED/csal_ipc_message_subscribequeue.o

# target to build an object file
src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.o
.PHONY : src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.o

src/CHAL_SHARED/csal_ipc_message_subscribequeue.i: src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.i
.PHONY : src/CHAL_SHARED/csal_ipc_message_subscribequeue.i

# target to preprocess a source file
src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.i
.PHONY : src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.i

src/CHAL_SHARED/csal_ipc_message_subscribequeue.s: src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.s
.PHONY : src/CHAL_SHARED/csal_ipc_message_subscribequeue.s

# target to generate assembly for a file
src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.s
.PHONY : src/CHAL_SHARED/csal_ipc_message_subscribequeue.cpp.s

src/CHAL_SHARED/csal_ipc_thread.o: src/CHAL_SHARED/csal_ipc_thread.cpp.o
.PHONY : src/CHAL_SHARED/csal_ipc_thread.o

# target to build an object file
src/CHAL_SHARED/csal_ipc_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc_thread.cpp.o
.PHONY : src/CHAL_SHARED/csal_ipc_thread.cpp.o

src/CHAL_SHARED/csal_ipc_thread.i: src/CHAL_SHARED/csal_ipc_thread.cpp.i
.PHONY : src/CHAL_SHARED/csal_ipc_thread.i

# target to preprocess a source file
src/CHAL_SHARED/csal_ipc_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc_thread.cpp.i
.PHONY : src/CHAL_SHARED/csal_ipc_thread.cpp.i

src/CHAL_SHARED/csal_ipc_thread.s: src/CHAL_SHARED/csal_ipc_thread.cpp.s
.PHONY : src/CHAL_SHARED/csal_ipc_thread.s

# target to generate assembly for a file
src/CHAL_SHARED/csal_ipc_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ipc_thread.cpp.s
.PHONY : src/CHAL_SHARED/csal_ipc_thread.cpp.s

src/CHAL_SHARED/csal_ledmatrix.o: src/CHAL_SHARED/csal_ledmatrix.cpp.o
.PHONY : src/CHAL_SHARED/csal_ledmatrix.o

# target to build an object file
src/CHAL_SHARED/csal_ledmatrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ledmatrix.cpp.o
.PHONY : src/CHAL_SHARED/csal_ledmatrix.cpp.o

src/CHAL_SHARED/csal_ledmatrix.i: src/CHAL_SHARED/csal_ledmatrix.cpp.i
.PHONY : src/CHAL_SHARED/csal_ledmatrix.i

# target to preprocess a source file
src/CHAL_SHARED/csal_ledmatrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ledmatrix.cpp.i
.PHONY : src/CHAL_SHARED/csal_ledmatrix.cpp.i

src/CHAL_SHARED/csal_ledmatrix.s: src/CHAL_SHARED/csal_ledmatrix.cpp.s
.PHONY : src/CHAL_SHARED/csal_ledmatrix.s

# target to generate assembly for a file
src/CHAL_SHARED/csal_ledmatrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/csal_ledmatrix.cpp.s
.PHONY : src/CHAL_SHARED/csal_ledmatrix.cpp.s

src/CHAL_SHARED/os_led_strip.o: src/CHAL_SHARED/os_led_strip.cpp.o
.PHONY : src/CHAL_SHARED/os_led_strip.o

# target to build an object file
src/CHAL_SHARED/os_led_strip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/os_led_strip.cpp.o
.PHONY : src/CHAL_SHARED/os_led_strip.cpp.o

src/CHAL_SHARED/os_led_strip.i: src/CHAL_SHARED/os_led_strip.cpp.i
.PHONY : src/CHAL_SHARED/os_led_strip.i

# target to preprocess a source file
src/CHAL_SHARED/os_led_strip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/os_led_strip.cpp.i
.PHONY : src/CHAL_SHARED/os_led_strip.cpp.i

src/CHAL_SHARED/os_led_strip.s: src/CHAL_SHARED/os_led_strip.cpp.s
.PHONY : src/CHAL_SHARED/os_led_strip.s

# target to generate assembly for a file
src/CHAL_SHARED/os_led_strip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CHAL_SHARED/os_led_strip.cpp.s
.PHONY : src/CHAL_SHARED/os_led_strip.cpp.s

src/CSAL_SHARED/event_management.o: src/CSAL_SHARED/event_management.cpp.o
.PHONY : src/CSAL_SHARED/event_management.o

# target to build an object file
src/CSAL_SHARED/event_management.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/event_management.cpp.o
.PHONY : src/CSAL_SHARED/event_management.cpp.o

src/CSAL_SHARED/event_management.i: src/CSAL_SHARED/event_management.cpp.i
.PHONY : src/CSAL_SHARED/event_management.i

# target to preprocess a source file
src/CSAL_SHARED/event_management.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/event_management.cpp.i
.PHONY : src/CSAL_SHARED/event_management.cpp.i

src/CSAL_SHARED/event_management.s: src/CSAL_SHARED/event_management.cpp.s
.PHONY : src/CSAL_SHARED/event_management.s

# target to generate assembly for a file
src/CSAL_SHARED/event_management.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/event_management.cpp.s
.PHONY : src/CSAL_SHARED/event_management.cpp.s

src/CSAL_SHARED/local_eventqueue.o: src/CSAL_SHARED/local_eventqueue.cpp.o
.PHONY : src/CSAL_SHARED/local_eventqueue.o

# target to build an object file
src/CSAL_SHARED/local_eventqueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/local_eventqueue.cpp.o
.PHONY : src/CSAL_SHARED/local_eventqueue.cpp.o

src/CSAL_SHARED/local_eventqueue.i: src/CSAL_SHARED/local_eventqueue.cpp.i
.PHONY : src/CSAL_SHARED/local_eventqueue.i

# target to preprocess a source file
src/CSAL_SHARED/local_eventqueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/local_eventqueue.cpp.i
.PHONY : src/CSAL_SHARED/local_eventqueue.cpp.i

src/CSAL_SHARED/local_eventqueue.s: src/CSAL_SHARED/local_eventqueue.cpp.s
.PHONY : src/CSAL_SHARED/local_eventqueue.s

# target to generate assembly for a file
src/CSAL_SHARED/local_eventqueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/local_eventqueue.cpp.s
.PHONY : src/CSAL_SHARED/local_eventqueue.cpp.s

src/CSAL_SHARED/lp_workqueue.o: src/CSAL_SHARED/lp_workqueue.cpp.o
.PHONY : src/CSAL_SHARED/lp_workqueue.o

# target to build an object file
src/CSAL_SHARED/lp_workqueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/lp_workqueue.cpp.o
.PHONY : src/CSAL_SHARED/lp_workqueue.cpp.o

src/CSAL_SHARED/lp_workqueue.i: src/CSAL_SHARED/lp_workqueue.cpp.i
.PHONY : src/CSAL_SHARED/lp_workqueue.i

# target to preprocess a source file
src/CSAL_SHARED/lp_workqueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/lp_workqueue.cpp.i
.PHONY : src/CSAL_SHARED/lp_workqueue.cpp.i

src/CSAL_SHARED/lp_workqueue.s: src/CSAL_SHARED/lp_workqueue.cpp.s
.PHONY : src/CSAL_SHARED/lp_workqueue.s

# target to generate assembly for a file
src/CSAL_SHARED/lp_workqueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/lp_workqueue.cpp.s
.PHONY : src/CSAL_SHARED/lp_workqueue.cpp.s

src/CSAL_SHARED/os_cli.o: src/CSAL_SHARED/os_cli.cpp.o
.PHONY : src/CSAL_SHARED/os_cli.o

# target to build an object file
src/CSAL_SHARED/os_cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/os_cli.cpp.o
.PHONY : src/CSAL_SHARED/os_cli.cpp.o

src/CSAL_SHARED/os_cli.i: src/CSAL_SHARED/os_cli.cpp.i
.PHONY : src/CSAL_SHARED/os_cli.i

# target to preprocess a source file
src/CSAL_SHARED/os_cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/os_cli.cpp.i
.PHONY : src/CSAL_SHARED/os_cli.cpp.i

src/CSAL_SHARED/os_cli.s: src/CSAL_SHARED/os_cli.cpp.s
.PHONY : src/CSAL_SHARED/os_cli.s

# target to generate assembly for a file
src/CSAL_SHARED/os_cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/os_cli.cpp.s
.PHONY : src/CSAL_SHARED/os_cli.cpp.s

src/CSAL_SHARED/os_error.o: src/CSAL_SHARED/os_error.cpp.o
.PHONY : src/CSAL_SHARED/os_error.o

# target to build an object file
src/CSAL_SHARED/os_error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/os_error.cpp.o
.PHONY : src/CSAL_SHARED/os_error.cpp.o

src/CSAL_SHARED/os_error.i: src/CSAL_SHARED/os_error.cpp.i
.PHONY : src/CSAL_SHARED/os_error.i

# target to preprocess a source file
src/CSAL_SHARED/os_error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/os_error.cpp.i
.PHONY : src/CSAL_SHARED/os_error.cpp.i

src/CSAL_SHARED/os_error.s: src/CSAL_SHARED/os_error.cpp.s
.PHONY : src/CSAL_SHARED/os_error.s

# target to generate assembly for a file
src/CSAL_SHARED/os_error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/os_error.cpp.s
.PHONY : src/CSAL_SHARED/os_error.cpp.s

src/CSAL_SHARED/os_quick_fft.o: src/CSAL_SHARED/os_quick_fft.cpp.o
.PHONY : src/CSAL_SHARED/os_quick_fft.o

# target to build an object file
src/CSAL_SHARED/os_quick_fft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/os_quick_fft.cpp.o
.PHONY : src/CSAL_SHARED/os_quick_fft.cpp.o

src/CSAL_SHARED/os_quick_fft.i: src/CSAL_SHARED/os_quick_fft.cpp.i
.PHONY : src/CSAL_SHARED/os_quick_fft.i

# target to preprocess a source file
src/CSAL_SHARED/os_quick_fft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/os_quick_fft.cpp.i
.PHONY : src/CSAL_SHARED/os_quick_fft.cpp.i

src/CSAL_SHARED/os_quick_fft.s: src/CSAL_SHARED/os_quick_fft.cpp.s
.PHONY : src/CSAL_SHARED/os_quick_fft.s

# target to generate assembly for a file
src/CSAL_SHARED/os_quick_fft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/os_quick_fft.cpp.s
.PHONY : src/CSAL_SHARED/os_quick_fft.cpp.s

src/CSAL_SHARED/safe_circular_queue.o: src/CSAL_SHARED/safe_circular_queue.cpp.o
.PHONY : src/CSAL_SHARED/safe_circular_queue.o

# target to build an object file
src/CSAL_SHARED/safe_circular_queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/safe_circular_queue.cpp.o
.PHONY : src/CSAL_SHARED/safe_circular_queue.cpp.o

src/CSAL_SHARED/safe_circular_queue.i: src/CSAL_SHARED/safe_circular_queue.cpp.i
.PHONY : src/CSAL_SHARED/safe_circular_queue.i

# target to preprocess a source file
src/CSAL_SHARED/safe_circular_queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/safe_circular_queue.cpp.i
.PHONY : src/CSAL_SHARED/safe_circular_queue.cpp.i

src/CSAL_SHARED/safe_circular_queue.s: src/CSAL_SHARED/safe_circular_queue.cpp.s
.PHONY : src/CSAL_SHARED/safe_circular_queue.s

# target to generate assembly for a file
src/CSAL_SHARED/safe_circular_queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/safe_circular_queue.cpp.s
.PHONY : src/CSAL_SHARED/safe_circular_queue.cpp.s

src/CSAL_SHARED/safe_fifo.o: src/CSAL_SHARED/safe_fifo.cpp.o
.PHONY : src/CSAL_SHARED/safe_fifo.o

# target to build an object file
src/CSAL_SHARED/safe_fifo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/safe_fifo.cpp.o
.PHONY : src/CSAL_SHARED/safe_fifo.cpp.o

src/CSAL_SHARED/safe_fifo.i: src/CSAL_SHARED/safe_fifo.cpp.i
.PHONY : src/CSAL_SHARED/safe_fifo.i

# target to preprocess a source file
src/CSAL_SHARED/safe_fifo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/safe_fifo.cpp.i
.PHONY : src/CSAL_SHARED/safe_fifo.cpp.i

src/CSAL_SHARED/safe_fifo.s: src/CSAL_SHARED/safe_fifo.cpp.s
.PHONY : src/CSAL_SHARED/safe_fifo.s

# target to generate assembly for a file
src/CSAL_SHARED/safe_fifo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/safe_fifo.cpp.s
.PHONY : src/CSAL_SHARED/safe_fifo.cpp.s

src/CSAL_SHARED/statemachine.o: src/CSAL_SHARED/statemachine.cpp.o
.PHONY : src/CSAL_SHARED/statemachine.o

# target to build an object file
src/CSAL_SHARED/statemachine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/statemachine.cpp.o
.PHONY : src/CSAL_SHARED/statemachine.cpp.o

src/CSAL_SHARED/statemachine.i: src/CSAL_SHARED/statemachine.cpp.i
.PHONY : src/CSAL_SHARED/statemachine.i

# target to preprocess a source file
src/CSAL_SHARED/statemachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/statemachine.cpp.i
.PHONY : src/CSAL_SHARED/statemachine.cpp.i

src/CSAL_SHARED/statemachine.s: src/CSAL_SHARED/statemachine.cpp.s
.PHONY : src/CSAL_SHARED/statemachine.s

# target to generate assembly for a file
src/CSAL_SHARED/statemachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/statemachine.cpp.s
.PHONY : src/CSAL_SHARED/statemachine.cpp.s

src/CSAL_SHARED/thread_init.o: src/CSAL_SHARED/thread_init.cpp.o
.PHONY : src/CSAL_SHARED/thread_init.o

# target to build an object file
src/CSAL_SHARED/thread_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/thread_init.cpp.o
.PHONY : src/CSAL_SHARED/thread_init.cpp.o

src/CSAL_SHARED/thread_init.i: src/CSAL_SHARED/thread_init.cpp.i
.PHONY : src/CSAL_SHARED/thread_init.i

# target to preprocess a source file
src/CSAL_SHARED/thread_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/thread_init.cpp.i
.PHONY : src/CSAL_SHARED/thread_init.cpp.i

src/CSAL_SHARED/thread_init.s: src/CSAL_SHARED/thread_init.cpp.s
.PHONY : src/CSAL_SHARED/thread_init.s

# target to generate assembly for a file
src/CSAL_SHARED/thread_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/thread_init.cpp.s
.PHONY : src/CSAL_SHARED/thread_init.cpp.s

src/CSAL_SHARED/unit_check.o: src/CSAL_SHARED/unit_check.cpp.o
.PHONY : src/CSAL_SHARED/unit_check.o

# target to build an object file
src/CSAL_SHARED/unit_check.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/unit_check.cpp.o
.PHONY : src/CSAL_SHARED/unit_check.cpp.o

src/CSAL_SHARED/unit_check.i: src/CSAL_SHARED/unit_check.cpp.i
.PHONY : src/CSAL_SHARED/unit_check.i

# target to preprocess a source file
src/CSAL_SHARED/unit_check.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/unit_check.cpp.i
.PHONY : src/CSAL_SHARED/unit_check.cpp.i

src/CSAL_SHARED/unit_check.s: src/CSAL_SHARED/unit_check.cpp.s
.PHONY : src/CSAL_SHARED/unit_check.s

# target to generate assembly for a file
src/CSAL_SHARED/unit_check.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/unit_check.cpp.s
.PHONY : src/CSAL_SHARED/unit_check.cpp.s

src/CSAL_SHARED/unsafe_fifo.o: src/CSAL_SHARED/unsafe_fifo.cpp.o
.PHONY : src/CSAL_SHARED/unsafe_fifo.o

# target to build an object file
src/CSAL_SHARED/unsafe_fifo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/unsafe_fifo.cpp.o
.PHONY : src/CSAL_SHARED/unsafe_fifo.cpp.o

src/CSAL_SHARED/unsafe_fifo.i: src/CSAL_SHARED/unsafe_fifo.cpp.i
.PHONY : src/CSAL_SHARED/unsafe_fifo.i

# target to preprocess a source file
src/CSAL_SHARED/unsafe_fifo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/unsafe_fifo.cpp.i
.PHONY : src/CSAL_SHARED/unsafe_fifo.cpp.i

src/CSAL_SHARED/unsafe_fifo.s: src/CSAL_SHARED/unsafe_fifo.cpp.s
.PHONY : src/CSAL_SHARED/unsafe_fifo.s

# target to generate assembly for a file
src/CSAL_SHARED/unsafe_fifo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/CSAL_SHARED/unsafe_fifo.cpp.s
.PHONY : src/CSAL_SHARED/unsafe_fifo.cpp.s

src/LinuxCHAL/os_adc.o: src/LinuxCHAL/os_adc.cpp.o
.PHONY : src/LinuxCHAL/os_adc.o

# target to build an object file
src/LinuxCHAL/os_adc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_adc.cpp.o
.PHONY : src/LinuxCHAL/os_adc.cpp.o

src/LinuxCHAL/os_adc.i: src/LinuxCHAL/os_adc.cpp.i
.PHONY : src/LinuxCHAL/os_adc.i

# target to preprocess a source file
src/LinuxCHAL/os_adc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_adc.cpp.i
.PHONY : src/LinuxCHAL/os_adc.cpp.i

src/LinuxCHAL/os_adc.s: src/LinuxCHAL/os_adc.cpp.s
.PHONY : src/LinuxCHAL/os_adc.s

# target to generate assembly for a file
src/LinuxCHAL/os_adc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_adc.cpp.s
.PHONY : src/LinuxCHAL/os_adc.cpp.s

src/LinuxCHAL/os_gpio.o: src/LinuxCHAL/os_gpio.cpp.o
.PHONY : src/LinuxCHAL/os_gpio.o

# target to build an object file
src/LinuxCHAL/os_gpio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_gpio.cpp.o
.PHONY : src/LinuxCHAL/os_gpio.cpp.o

src/LinuxCHAL/os_gpio.i: src/LinuxCHAL/os_gpio.cpp.i
.PHONY : src/LinuxCHAL/os_gpio.i

# target to preprocess a source file
src/LinuxCHAL/os_gpio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_gpio.cpp.i
.PHONY : src/LinuxCHAL/os_gpio.cpp.i

src/LinuxCHAL/os_gpio.s: src/LinuxCHAL/os_gpio.cpp.s
.PHONY : src/LinuxCHAL/os_gpio.s

# target to generate assembly for a file
src/LinuxCHAL/os_gpio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_gpio.cpp.s
.PHONY : src/LinuxCHAL/os_gpio.cpp.s

src/LinuxCHAL/os_i2c.o: src/LinuxCHAL/os_i2c.cpp.o
.PHONY : src/LinuxCHAL/os_i2c.o

# target to build an object file
src/LinuxCHAL/os_i2c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_i2c.cpp.o
.PHONY : src/LinuxCHAL/os_i2c.cpp.o

src/LinuxCHAL/os_i2c.i: src/LinuxCHAL/os_i2c.cpp.i
.PHONY : src/LinuxCHAL/os_i2c.i

# target to preprocess a source file
src/LinuxCHAL/os_i2c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_i2c.cpp.i
.PHONY : src/LinuxCHAL/os_i2c.cpp.i

src/LinuxCHAL/os_i2c.s: src/LinuxCHAL/os_i2c.cpp.s
.PHONY : src/LinuxCHAL/os_i2c.s

# target to generate assembly for a file
src/LinuxCHAL/os_i2c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_i2c.cpp.s
.PHONY : src/LinuxCHAL/os_i2c.cpp.s

src/LinuxCHAL/os_spi.o: src/LinuxCHAL/os_spi.cpp.o
.PHONY : src/LinuxCHAL/os_spi.o

# target to build an object file
src/LinuxCHAL/os_spi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_spi.cpp.o
.PHONY : src/LinuxCHAL/os_spi.cpp.o

src/LinuxCHAL/os_spi.i: src/LinuxCHAL/os_spi.cpp.i
.PHONY : src/LinuxCHAL/os_spi.i

# target to preprocess a source file
src/LinuxCHAL/os_spi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_spi.cpp.i
.PHONY : src/LinuxCHAL/os_spi.cpp.i

src/LinuxCHAL/os_spi.s: src/LinuxCHAL/os_spi.cpp.s
.PHONY : src/LinuxCHAL/os_spi.s

# target to generate assembly for a file
src/LinuxCHAL/os_spi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_spi.cpp.s
.PHONY : src/LinuxCHAL/os_spi.cpp.s

src/LinuxCHAL/os_uart.o: src/LinuxCHAL/os_uart.cpp.o
.PHONY : src/LinuxCHAL/os_uart.o

# target to build an object file
src/LinuxCHAL/os_uart.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_uart.cpp.o
.PHONY : src/LinuxCHAL/os_uart.cpp.o

src/LinuxCHAL/os_uart.i: src/LinuxCHAL/os_uart.cpp.i
.PHONY : src/LinuxCHAL/os_uart.i

# target to preprocess a source file
src/LinuxCHAL/os_uart.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_uart.cpp.i
.PHONY : src/LinuxCHAL/os_uart.cpp.i

src/LinuxCHAL/os_uart.s: src/LinuxCHAL/os_uart.cpp.s
.PHONY : src/LinuxCHAL/os_uart.s

# target to generate assembly for a file
src/LinuxCHAL/os_uart.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_uart.cpp.s
.PHONY : src/LinuxCHAL/os_uart.cpp.s

src/LinuxCHAL/os_wifi.o: src/LinuxCHAL/os_wifi.cpp.o
.PHONY : src/LinuxCHAL/os_wifi.o

# target to build an object file
src/LinuxCHAL/os_wifi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_wifi.cpp.o
.PHONY : src/LinuxCHAL/os_wifi.cpp.o

src/LinuxCHAL/os_wifi.i: src/LinuxCHAL/os_wifi.cpp.i
.PHONY : src/LinuxCHAL/os_wifi.i

# target to preprocess a source file
src/LinuxCHAL/os_wifi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_wifi.cpp.i
.PHONY : src/LinuxCHAL/os_wifi.cpp.i

src/LinuxCHAL/os_wifi.s: src/LinuxCHAL/os_wifi.cpp.s
.PHONY : src/LinuxCHAL/os_wifi.s

# target to generate assembly for a file
src/LinuxCHAL/os_wifi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCHAL/os_wifi.cpp.s
.PHONY : src/LinuxCHAL/os_wifi.cpp.s

src/LinuxCSAL/os_error.o: src/LinuxCSAL/os_error.cpp.o
.PHONY : src/LinuxCSAL/os_error.o

# target to build an object file
src/LinuxCSAL/os_error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_error.cpp.o
.PHONY : src/LinuxCSAL/os_error.cpp.o

src/LinuxCSAL/os_error.i: src/LinuxCSAL/os_error.cpp.i
.PHONY : src/LinuxCSAL/os_error.i

# target to preprocess a source file
src/LinuxCSAL/os_error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_error.cpp.i
.PHONY : src/LinuxCSAL/os_error.cpp.i

src/LinuxCSAL/os_error.s: src/LinuxCSAL/os_error.cpp.s
.PHONY : src/LinuxCSAL/os_error.s

# target to generate assembly for a file
src/LinuxCSAL/os_error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_error.cpp.s
.PHONY : src/LinuxCSAL/os_error.cpp.s

src/LinuxCSAL/os_misc.o: src/LinuxCSAL/os_misc.cpp.o
.PHONY : src/LinuxCSAL/os_misc.o

# target to build an object file
src/LinuxCSAL/os_misc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_misc.cpp.o
.PHONY : src/LinuxCSAL/os_misc.cpp.o

src/LinuxCSAL/os_misc.i: src/LinuxCSAL/os_misc.cpp.i
.PHONY : src/LinuxCSAL/os_misc.i

# target to preprocess a source file
src/LinuxCSAL/os_misc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_misc.cpp.i
.PHONY : src/LinuxCSAL/os_misc.cpp.i

src/LinuxCSAL/os_misc.s: src/LinuxCSAL/os_misc.cpp.s
.PHONY : src/LinuxCSAL/os_misc.s

# target to generate assembly for a file
src/LinuxCSAL/os_misc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_misc.cpp.s
.PHONY : src/LinuxCSAL/os_misc.cpp.s

src/LinuxCSAL/os_mutx.o: src/LinuxCSAL/os_mutx.cpp.o
.PHONY : src/LinuxCSAL/os_mutx.o

# target to build an object file
src/LinuxCSAL/os_mutx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_mutx.cpp.o
.PHONY : src/LinuxCSAL/os_mutx.cpp.o

src/LinuxCSAL/os_mutx.i: src/LinuxCSAL/os_mutx.cpp.i
.PHONY : src/LinuxCSAL/os_mutx.i

# target to preprocess a source file
src/LinuxCSAL/os_mutx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_mutx.cpp.i
.PHONY : src/LinuxCSAL/os_mutx.cpp.i

src/LinuxCSAL/os_mutx.s: src/LinuxCSAL/os_mutx.cpp.s
.PHONY : src/LinuxCSAL/os_mutx.s

# target to generate assembly for a file
src/LinuxCSAL/os_mutx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_mutx.cpp.s
.PHONY : src/LinuxCSAL/os_mutx.cpp.s

src/LinuxCSAL/os_sem.o: src/LinuxCSAL/os_sem.cpp.o
.PHONY : src/LinuxCSAL/os_sem.o

# target to build an object file
src/LinuxCSAL/os_sem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_sem.cpp.o
.PHONY : src/LinuxCSAL/os_sem.cpp.o

src/LinuxCSAL/os_sem.i: src/LinuxCSAL/os_sem.cpp.i
.PHONY : src/LinuxCSAL/os_sem.i

# target to preprocess a source file
src/LinuxCSAL/os_sem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_sem.cpp.i
.PHONY : src/LinuxCSAL/os_sem.cpp.i

src/LinuxCSAL/os_sem.s: src/LinuxCSAL/os_sem.cpp.s
.PHONY : src/LinuxCSAL/os_sem.s

# target to generate assembly for a file
src/LinuxCSAL/os_sem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_sem.cpp.s
.PHONY : src/LinuxCSAL/os_sem.cpp.s

src/LinuxCSAL/os_setbits.o: src/LinuxCSAL/os_setbits.cpp.o
.PHONY : src/LinuxCSAL/os_setbits.o

# target to build an object file
src/LinuxCSAL/os_setbits.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_setbits.cpp.o
.PHONY : src/LinuxCSAL/os_setbits.cpp.o

src/LinuxCSAL/os_setbits.i: src/LinuxCSAL/os_setbits.cpp.i
.PHONY : src/LinuxCSAL/os_setbits.i

# target to preprocess a source file
src/LinuxCSAL/os_setbits.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_setbits.cpp.i
.PHONY : src/LinuxCSAL/os_setbits.cpp.i

src/LinuxCSAL/os_setbits.s: src/LinuxCSAL/os_setbits.cpp.s
.PHONY : src/LinuxCSAL/os_setbits.s

# target to generate assembly for a file
src/LinuxCSAL/os_setbits.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_setbits.cpp.s
.PHONY : src/LinuxCSAL/os_setbits.cpp.s

src/LinuxCSAL/os_thread.o: src/LinuxCSAL/os_thread.cpp.o
.PHONY : src/LinuxCSAL/os_thread.o

# target to build an object file
src/LinuxCSAL/os_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_thread.cpp.o
.PHONY : src/LinuxCSAL/os_thread.cpp.o

src/LinuxCSAL/os_thread.i: src/LinuxCSAL/os_thread.cpp.i
.PHONY : src/LinuxCSAL/os_thread.i

# target to preprocess a source file
src/LinuxCSAL/os_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_thread.cpp.i
.PHONY : src/LinuxCSAL/os_thread.cpp.i

src/LinuxCSAL/os_thread.s: src/LinuxCSAL/os_thread.cpp.s
.PHONY : src/LinuxCSAL/os_thread.s

# target to generate assembly for a file
src/LinuxCSAL/os_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/LinuxCSAL/os_thread.cpp.s
.PHONY : src/LinuxCSAL/os_thread.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PosixExample.dir/build.make CMakeFiles/PosixExample.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PosixExample"
	@echo "... src/CHAL_SHARED/color_conv.o"
	@echo "... src/CHAL_SHARED/color_conv.i"
	@echo "... src/CHAL_SHARED/color_conv.s"
	@echo "... src/CHAL_SHARED/csal_ipc.o"
	@echo "... src/CHAL_SHARED/csal_ipc.i"
	@echo "... src/CHAL_SHARED/csal_ipc.s"
	@echo "... src/CHAL_SHARED/csal_ipc_message_publishqueue.o"
	@echo "... src/CHAL_SHARED/csal_ipc_message_publishqueue.i"
	@echo "... src/CHAL_SHARED/csal_ipc_message_publishqueue.s"
	@echo "... src/CHAL_SHARED/csal_ipc_message_subscribequeue.o"
	@echo "... src/CHAL_SHARED/csal_ipc_message_subscribequeue.i"
	@echo "... src/CHAL_SHARED/csal_ipc_message_subscribequeue.s"
	@echo "... src/CHAL_SHARED/csal_ipc_thread.o"
	@echo "... src/CHAL_SHARED/csal_ipc_thread.i"
	@echo "... src/CHAL_SHARED/csal_ipc_thread.s"
	@echo "... src/CHAL_SHARED/csal_ledmatrix.o"
	@echo "... src/CHAL_SHARED/csal_ledmatrix.i"
	@echo "... src/CHAL_SHARED/csal_ledmatrix.s"
	@echo "... src/CHAL_SHARED/os_led_strip.o"
	@echo "... src/CHAL_SHARED/os_led_strip.i"
	@echo "... src/CHAL_SHARED/os_led_strip.s"
	@echo "... src/CSAL_SHARED/event_management.o"
	@echo "... src/CSAL_SHARED/event_management.i"
	@echo "... src/CSAL_SHARED/event_management.s"
	@echo "... src/CSAL_SHARED/local_eventqueue.o"
	@echo "... src/CSAL_SHARED/local_eventqueue.i"
	@echo "... src/CSAL_SHARED/local_eventqueue.s"
	@echo "... src/CSAL_SHARED/lp_workqueue.o"
	@echo "... src/CSAL_SHARED/lp_workqueue.i"
	@echo "... src/CSAL_SHARED/lp_workqueue.s"
	@echo "... src/CSAL_SHARED/os_cli.o"
	@echo "... src/CSAL_SHARED/os_cli.i"
	@echo "... src/CSAL_SHARED/os_cli.s"
	@echo "... src/CSAL_SHARED/os_error.o"
	@echo "... src/CSAL_SHARED/os_error.i"
	@echo "... src/CSAL_SHARED/os_error.s"
	@echo "... src/CSAL_SHARED/os_quick_fft.o"
	@echo "... src/CSAL_SHARED/os_quick_fft.i"
	@echo "... src/CSAL_SHARED/os_quick_fft.s"
	@echo "... src/CSAL_SHARED/safe_circular_queue.o"
	@echo "... src/CSAL_SHARED/safe_circular_queue.i"
	@echo "... src/CSAL_SHARED/safe_circular_queue.s"
	@echo "... src/CSAL_SHARED/safe_fifo.o"
	@echo "... src/CSAL_SHARED/safe_fifo.i"
	@echo "... src/CSAL_SHARED/safe_fifo.s"
	@echo "... src/CSAL_SHARED/statemachine.o"
	@echo "... src/CSAL_SHARED/statemachine.i"
	@echo "... src/CSAL_SHARED/statemachine.s"
	@echo "... src/CSAL_SHARED/thread_init.o"
	@echo "... src/CSAL_SHARED/thread_init.i"
	@echo "... src/CSAL_SHARED/thread_init.s"
	@echo "... src/CSAL_SHARED/unit_check.o"
	@echo "... src/CSAL_SHARED/unit_check.i"
	@echo "... src/CSAL_SHARED/unit_check.s"
	@echo "... src/CSAL_SHARED/unsafe_fifo.o"
	@echo "... src/CSAL_SHARED/unsafe_fifo.i"
	@echo "... src/CSAL_SHARED/unsafe_fifo.s"
	@echo "... src/LinuxCHAL/os_adc.o"
	@echo "... src/LinuxCHAL/os_adc.i"
	@echo "... src/LinuxCHAL/os_adc.s"
	@echo "... src/LinuxCHAL/os_gpio.o"
	@echo "... src/LinuxCHAL/os_gpio.i"
	@echo "... src/LinuxCHAL/os_gpio.s"
	@echo "... src/LinuxCHAL/os_i2c.o"
	@echo "... src/LinuxCHAL/os_i2c.i"
	@echo "... src/LinuxCHAL/os_i2c.s"
	@echo "... src/LinuxCHAL/os_spi.o"
	@echo "... src/LinuxCHAL/os_spi.i"
	@echo "... src/LinuxCHAL/os_spi.s"
	@echo "... src/LinuxCHAL/os_uart.o"
	@echo "... src/LinuxCHAL/os_uart.i"
	@echo "... src/LinuxCHAL/os_uart.s"
	@echo "... src/LinuxCHAL/os_wifi.o"
	@echo "... src/LinuxCHAL/os_wifi.i"
	@echo "... src/LinuxCHAL/os_wifi.s"
	@echo "... src/LinuxCSAL/os_error.o"
	@echo "... src/LinuxCSAL/os_error.i"
	@echo "... src/LinuxCSAL/os_error.s"
	@echo "... src/LinuxCSAL/os_misc.o"
	@echo "... src/LinuxCSAL/os_misc.i"
	@echo "... src/LinuxCSAL/os_misc.s"
	@echo "... src/LinuxCSAL/os_mutx.o"
	@echo "... src/LinuxCSAL/os_mutx.i"
	@echo "... src/LinuxCSAL/os_mutx.s"
	@echo "... src/LinuxCSAL/os_sem.o"
	@echo "... src/LinuxCSAL/os_sem.i"
	@echo "... src/LinuxCSAL/os_sem.s"
	@echo "... src/LinuxCSAL/os_setbits.o"
	@echo "... src/LinuxCSAL/os_setbits.i"
	@echo "... src/LinuxCSAL/os_setbits.s"
	@echo "... src/LinuxCSAL/os_thread.o"
	@echo "... src/LinuxCSAL/os_thread.i"
	@echo "... src/LinuxCSAL/os_thread.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

